# servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-monitor
  namespace: grafana-prometheus-stack
  labels:
    app: scaletestapp
    release: grafana-stack
spec:
  selector:
    matchLabels:
      app: scaletestapp
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - default
